/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef FLOAT_SIGNAL_H
#define FLOAT_SIGNAL_H

#include <stdint.h>


#ifdef __cplusplus
extern "C" { 
#endif

typedef struct {
	uint8_t ATar : 8; /* scaling 0.1, offset -12.5, units none  */
	uint16_t SpdTar : 16; /* scaling 0.0, offset 0.0, units km/h  */
	uint8_t LogCtrlUrgency : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t LogCtrlMod : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageCounter : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageChecksum : 4; /* scaling 1.0, offset 0.0, units none  */
} LogCmdMai_t;


#ifdef __cplusplus
} 
#endif

#endif
