/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef DISPATCH_H
#define DISPATCH_H

#include <stdint.h>


#ifdef __cplusplus
extern "C" { 
#endif

typedef struct {
	uint8_t TiRemn : 8; /* scaling 1.0, offset 0.0, units hr  */
	uint8_t SOC : 8; /* scaling 1.0, offset 0.0, units %  */
	uint8_t SOH : 8; /* scaling 1.0, offset 0.0, units %  */
	int16_t AuxBattVolt : 16; /* scaling 0.0, offset 0.0, units V  */
	int16_t AuxBattCurr : 16; /* scaling 0.1, offset 0.0, units A  */
	uint8_t AuxBattErr : 8; /* scaling 1.0, offset 0.0, units none  */
} BMSRpt1_t;

typedef struct {
	uint8_t RlySts : 2; /* scaling 1.0, offset 0.0, units none  */
	uint16_t StrtgBattVolt : 16; /* scaling 0.0, offset 0.0, units V  */
} BMSRpt2_t;

typedef struct {
} EnvRpt1_t;

typedef struct {
	uint16_t GrossCombinationVehicleWeight : 16; /* scaling 10.0, offset 0.0, units kg  */
	uint8_t RainStatus : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t WindShieldWiperStatus : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SpdFwrVeh : 8; /* scaling 1.0, offset 0.0, units km/h  */
	uint8_t DisTFwrVeh : 8; /* scaling 1.0, offset 0.0, units m  */
} GenRpt1_t;

typedef struct {
	uint8_t OperMod : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SetT : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ReqdFanSpd : 8; /* scaling 1.0, offset 0.0, units none  */
	uint16_t CbnT : 16; /* scaling 0.0, offset 0.0, units none  */
} AcCmdRpt_t;

typedef struct {
	uint8_t AcFlt : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CtrlMod : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t AcSts : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CmprSpd : 8; /* scaling 1.0, offset 0.0, units none  */
	uint16_t AcT : 16; /* scaling 1.0, offset 0.0, units none  */
	uint16_t SvrT : 16; /* scaling 1.0, offset 0.0, units none  */
} AcRpt_t;

typedef struct {
	uint16_t SwtT : 16; /* scaling 0.1, offset -28.9, units deg C  */
	uint8_t TSevereWarn : 8; /* scaling 1.0, offset 0.0, units none  */
} SwtTRpt_t;

typedef struct {
	uint16_t AuxV : 16; /* scaling 0.5, offset 0.0, units mV  */
	uint8_t PwrSevereWarn : 8; /* scaling 1.0, offset 0.0, units none  */
} PwrRpt_t;

typedef struct {
	int16_t WP_x : 16; /* scaling 0.0, offset 0.0, units none  */
	int16_t WP_y : 16; /* scaling 0.0, offset 0.0, units none  */
	int16_t WP_speed : 16; /* scaling 0.0, offset 0.0, units none  */
	uint8_t Turn_Signal : 8; /* scaling 1.0, offset 0.0, units none  */
} ROS_WPoint_t;

typedef struct {
	int16_t Accel : 16; /* scaling 0.0, offset 150.0, units none  */
} ROS_Long_Control_t;

typedef struct {
	int16_t Steering : 16; /* scaling 0.0, offset -150.0, units none  */
} ROS_Lat_Control_t;

typedef struct {
	int16_t Speed : 16; /* scaling 0.0, offset -150.0, units none  */
} ROS_Log_Speed_t;

typedef struct {
	uint8_t Lat_Active : 8; /* scaling 1.0, offset 0.0, units none  */
} ROST_Active_Tri_t;

typedef struct {
	uint8_t LeftTurnSignalLightsCmd : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RightTurnSignalLightsCmd : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HazardLightSwitch : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LowBeamHeadLightCmd : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HighBeamHeadLightCmd : 2; /* scaling 1.0, offset 0.0, units none  */
} AcsyCmd_t;

typedef struct {
	int16_t angle_cmd : 16; /* scaling 0.0, offset 0.0, units rad  */
	int16_t steering_effort : 16; /* scaling 1.0, offset 0.0, units none  */
	uint8_t lat_enable_demand : 8; /* scaling 1.0, offset 0.0, units none  */
} ROS_LatCmd_t;

typedef struct {
	int16_t SteerCentrPosReq : 16; /* scaling 0.0, offset 0.0, units deg  */
} LatCmdOpt_t;

typedef struct {
	int16_t angle_manual : 16; /* scaling 0.0, offset 0.0, units none  */
	int16_t angle_cmd : 16; /* scaling 0.0, offset 0.0, units none  */
	int16_t angle_speed : 16; /* scaling 1.0, offset 0.0, units none  */
	int8_t HW_Torque : 8; /* scaling 1.0, offset 0.0, units none  */
} ROST_LatStReport_t;

typedef struct {
	int16_t yaw_rate : 16; /* scaling 1.0, offset 0.0, units none  */
	int16_t accel_y : 16; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Lat_Status : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Lat_Mode : 4; /* scaling 1.0, offset 0.0, units none  */
} ROST_LatReport_t;

typedef struct {
	int16_t accel_cmd : 16; /* scaling 0.0, offset 0.0, units m/s^2  */
	int8_t brake_limit : 8; /* scaling 0.0, offset 0.0, units none  */
	int8_t brake_tau : 8; /* scaling 0.1, offset 0.0, units none  */
	uint8_t xbr_ebi_mode : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t log_enable_demand : 8; /* scaling 1.0, offset 0.0, units none  */
} ROS_LogCmd_t;

typedef struct {
	uint8_t EngTqPercTar : 8; /* scaling 1.0, offset -125.0, units %  */
	uint8_t EngBrkTqPercTar : 8; /* scaling 1.0, offset -125.0, units %  */
	uint8_t GearTar : 8; /* scaling 1.0, offset -125.0, units none  */
	uint8_t BrkPTar : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t BrkArbn : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageCounter : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageChecksum : 4; /* scaling 1.0, offset 0.0, units none  */
} LogCmdOpt_t;

typedef struct {
	uint8_t accel_pedal : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t brake_pedal : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t remote_accel : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t SpdFwrVeh : 8; /* scaling 1.0, offset 0.0, units km/h  */
	uint8_t DisTFwrVeh : 8; /* scaling 1.0, offset 0.0, units m  */
	uint8_t VDC2_Long_Accel : 8; /* scaling 0.1, offset -12.5, units m/s^2  */
} ROST_LogPdlReport_t;

typedef struct {
	uint16_t current_speed : 16; /* scaling 0.0, offset 0.0, units none  */
	int16_t cmd_accel : 16; /* scaling 1.0, offset 0.0, units none  */
	uint8_t foundationbrakeuse : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Retarder_Torque : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Log_Status : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Log_Mode : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t AirBrake_Pressure : 8; /* scaling 1.0, offset 0.0, units none  */
} ROST_LogReport_t;

typedef struct {
	uint16_t current_torque : 16; /* scaling 0.1, offset 0.0, units none  */
	uint8_t engine_speed : 8; /* scaling 8.0, offset 0.0, units none  */
	uint8_t gear_ratio : 8; /* scaling 0.1, offset 0.0, units none  */
	uint8_t FuLvl1 : 8; /* scaling 0.4, offset 0.0, units none  */
	uint8_t FuLvl2 : 8; /* scaling 0.4, offset 0.0, units none  */
	uint8_t log_error_status : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t lat_error_status : 4; /* scaling 1.0, offset 0.0, units none  */
} ROST_GlobalReport_t;

typedef struct {
	uint8_t Target_Gear : 8; /* scaling 1.0, offset -125.0, units none  */
	uint8_t Target_EngineBrakePercentage : 8; /* scaling 1.0, offset -125.0, units %  */
} ROS_ModCmd_t;

typedef struct {
	uint16_t FrontAxleSpeed : 16; /* scaling 0.0, offset 0.0, units km/h  */
	uint8_t RelativeSpeedFrontAxleLeftWheel : 8; /* scaling 0.1, offset -7.8, units km/h  */
	uint8_t RelativeSpeedFrontAxleRightWheel : 8; /* scaling 0.1, offset -7.8, units km/h  */
	uint8_t RelativeSpeedRearAxle1LeftWheel : 8; /* scaling 0.1, offset -7.8, units km/h  */
	uint8_t RelativeSpeedRearAxle1RightWheel : 8; /* scaling 0.1, offset -7.8, units km/h  */
	uint8_t RelativeSpeedRearAxle2LeftWheel : 8; /* scaling 0.1, offset -7.8, units km/h  */
	uint8_t RelativeSpeedRearAxle2RightWheel : 8; /* scaling 0.1, offset -7.8, units km/h  */
} EBC2_8096_t;

typedef struct {
	uint8_t CurrentGear : 8; /* scaling 1.0, offset -125.0, units none  */
	uint8_t ActEngBrkPerc : 8; /* scaling 1.0, offset -125.0, units %  */
} ROST_ModReport_t;

typedef struct {
	uint16_t EngFuRate : 16; /* scaling 0.1, offset 0.0, units L/h  */
	uint16_t EngInstantaneousFuEco : 16; /* scaling 0.0, offset 0.0, units km/L  */
	uint16_t EngAvrgFuEco : 16; /* scaling 0.0, offset 0.0, units km/L  */
} ROST_FuelEconReport_t;

typedef struct {
	uint8_t SteerGearSts : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SteerColnSts : 4; /* scaling 1.0, offset 0.0, units none  */
	int16_t SteerColnCentrPos : 16; /* scaling 0.0, offset 0.0, units deg  */
	int16_t SteerGearCentrPos : 16; /* scaling 0.0, offset 0.0, units deg  */
	int16_t SteerTq : 16; /* scaling 0.0, offset 0.0, units Nm  */
	uint8_t MessageCounter : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageChecksum : 4; /* scaling 1.0, offset 0.0, units none  */
} SteerRpt2_t;

typedef struct {
	uint8_t SteerMod : 8; /* scaling 1.0, offset 0.0, units none  */
	int32_t SteerCmd : 32; /* scaling 0.0, offset 0.0, units deg  */
	uint8_t MessageCounter : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageChecksum : 4; /* scaling 1.0, offset 0.0, units none  */
} SteerGearCmdRpt_t;

typedef struct {
	uint8_t SteerMod : 8; /* scaling 1.0, offset 0.0, units none  */
	int32_t SteerCmd : 32; /* scaling 0.0, offset 0.0, units deg  */
	uint8_t MessageCounter : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageChecksum : 4; /* scaling 1.0, offset 0.0, units none  */
} SteerColnCmdRpt_t;

typedef struct {
	uint8_t EngSpd : 8; /* scaling 12.5, offset 0.0, units rpm  */
	uint8_t EngTq : 8; /* scaling 1.0, offset -125.0, units %  */
	uint8_t EngCooltT : 8; /* scaling 1.0, offset -40.0, units deg C  */
	uint8_t EngNomFricPerTq : 8; /* scaling 1.0, offset -125.0, units %  */
	uint8_t EstEngPrsiticLossesPercentTorque : 8; /* scaling 1.0, offset -125.0, units %  */
	uint8_t DriversDemandEngPercentTorque : 8; /* scaling 1.0, offset -125.0, units %  */
	uint8_t EngDemandPercentTorque : 8; /* scaling 1.0, offset -125.0, units %  */
	uint8_t ActlMaxAvailableEngPercentTorque : 8; /* scaling 0.4, offset 0.0, units %  */
} EngRpt1_t;

typedef struct {
	uint16_t EngFuRate : 16; /* scaling 0.1, offset 0.0, units L/h  */
	uint16_t EngInstantaneousFuEco : 16; /* scaling 0.0, offset 0.0, units km/L  */
	uint16_t EngAvrgFuEco : 16; /* scaling 0.0, offset 0.0, units km/L  */
	uint8_t FuLvl1 : 8; /* scaling 0.4, offset 0.0, units none  */
	uint8_t FuLvl2 : 8; /* scaling 0.4, offset 0.0, units none  */
} EngRpt2_t;

typedef struct {
	uint8_t EngSts : 4; /* scaling 1.0, offset 0.0, units none  */
	uint16_t EngSpeed : 16; /* scaling 0.1, offset 0.0, units rpm  */
} EngRpt3_t;

typedef struct {
	uint8_t CurrentGear : 8; /* scaling 1.0, offset -125.0, units none  */
	uint16_t TrsmOutSpd : 16; /* scaling 0.1, offset 0.0, units rpm  */
	uint16_t TrsmInSpd : 16; /* scaling 0.1, offset 0.0, units rpm  */
	int8_t TrsmShiftInProc : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TransDrivelineEngaged : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TransSelectedGear : 8; /* scaling 1.0, offset -125.0, units none  */
} TrsmRpt1_t;

typedef struct {
	uint16_t TrsmActGearRat : 16; /* scaling 0.0, offset 0.0, units none  */
	uint8_t TrsmSts : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EngRequestedTorque_TorqueLimit : 8; /* scaling 1.0, offset -125.0, units %  */
} TrsmRpt2_t;

typedef struct {
	uint8_t ActEngBrkTqPerc : 8; /* scaling 1.0, offset -125.0, units %  */
	uint8_t EngBrkSts : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ActlMxAvlblRetarderPercentTorque : 8; /* scaling 1.0, offset -125.0, units %  */
	uint8_t EngRequestedTorque_TorqueLimit : 8; /* scaling 1.0, offset -125.0, units %  */
} EngBrkRpt_t;

typedef struct {
	uint8_t PrimDelivery : 8; /* scaling 80.0, offset 0.0, units mbar  */
	uint8_t AirBrkSts : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t PrimDrvrPDmd : 8; /* scaling 80.0, offset 0.0, units mbar  */
	uint8_t XPRPReq : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t XPR1CtrlSts : 4; /* scaling 1.0, offset 0.0, units none  */
} AirBrkRpt1_t;

typedef struct {
	uint8_t LeftTurnSignalFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RightTurnSignalFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HazardLightFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RunningLightFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LowBeamHeadLightFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HighBeamHeadLightFail : 1; /* scaling 1.0, offset 0.0, units none  */
} LtgRpt_t;

typedef struct {
	int16_t AgCmd : 16; /* scaling 0.0, offset 0.0, units deg  */
	uint16_t SteerEffort : 16; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LatCtrlMod : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageCounter : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageChecksum : 4; /* scaling 1.0, offset 0.0, units none  */
} LatCmdMai_t;

typedef struct {
	int16_t SteerAgMan : 16; /* scaling 0.0, offset 0.0, units rad  */
	int16_t SteerAgCmd : 16; /* scaling 0.0, offset 0.0, units rad  */
	int16_t SteerSpd : 16; /* scaling 0.0, offset 0.0, units rev/sec  */
	uint8_t MessageCounter : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageChecksum : 4; /* scaling 1.0, offset 0.0, units none  */
} SteerRpt1_t;

typedef struct {
	uint16_t YawRate : 16; /* scaling 0.0, offset -3.9, units rad/s  */
	uint16_t A_y : 16; /* scaling 0.0, offset -15.7, units m/s2  */
	uint8_t LatSts : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageCounter : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageChecksum : 4; /* scaling 1.0, offset 0.0, units none  */
} VehLatRpt1_t;

typedef struct {
	uint8_t ATar : 8; /* scaling 0.1, offset -12.5, units none  */
	uint16_t SpdTar : 16; /* scaling 0.0, offset 0.0, units km/h  */
	uint8_t LogCtrlUrgency : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t LogCtrlMod : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageCounter : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MessageChecksum : 4; /* scaling 1.0, offset 0.0, units none  */
} LogCmdMai_t;

typedef struct {
	uint8_t DrvrAPedlPos : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t RemAPedlPos : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t BrkPedlPos : 8; /* scaling 0.4, offset 0.0, units %  */
	uint8_t DrvrBrkSwt : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LogSts : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t AccelPedalKickdownSwitch : 8; /* scaling 1.0, offset 0.0, units none  */
} VehLogRpt2_t;

typedef struct {
	uint8_t VehA : 8; /* scaling 0.1, offset -12.5, units none  */
	uint16_t VehSpd : 16; /* scaling 0.0, offset 0.0, units km/h  */
	uint8_t ATarFb : 8; /* scaling 0.1, offset -12.5, units none  */
	uint16_t SpdTarFb : 16; /* scaling 0.0, offset 0.0, units km/h  */
	uint8_t LogCtrlModFb : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LogCtrlUrgencyFb : 8; /* scaling 0.4, offset 0.0, units %  */
} VehLogRpt1_t;

typedef struct {
	uint8_t Day : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Hour : 8; /* scaling 1.0, offset 0.0, units hr  */
	uint8_t Minutes : 8; /* scaling 1.0, offset 0.0, units min  */
	uint8_t Seconds : 8; /* scaling 1.0, offset 0.0, units sec  */
	uint32_t RollingCounter : 32; /* scaling 1.0, offset 0.0, units none  */
} TimeSync_t;

typedef struct {
	uint8_t VehType : 4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t _2C2Present : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t P7Support : 2; /* scaling 1.0, offset 0.0, units none  */
} VehInfo_t;

typedef struct {
	uint8_t SystemStatus : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t PerceptionStatus : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LocalizationStatus : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t PlannerStatus : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ControllerStatus : 2; /* scaling 1.0, offset 0.0, units none  */
} OctopusStatus_t;

typedef struct {
	uint16_t HRW_FrontAxleLeftWheelSpeed : 16; /* scaling 0.0, offset 0.0, units km/h  */
	uint16_t HRW_FrontAxleRightWheelSpeed : 16; /* scaling 0.0, offset 0.0, units km/h  */
	uint16_t HRW_RearAxleLeftWheelSpeed : 16; /* scaling 0.0, offset 0.0, units km/h  */
	uint16_t HRW_RearAxleRightWheelSpeed : 16; /* scaling 0.0, offset 0.0, units km/h  */
} VehLogRpt4_t;

typedef struct {
	uint32_t SimTime : 32; /* scaling 1.0, offset 0.0, units none  */
	uint32_t RollingCounter : 32; /* scaling 1.0, offset 0.0, units none  */
} VcuTimeSync_t;

typedef struct {
	int16_t Current_Server : 16; /* scaling 0.1, offset -1600.0, units none  */
	int8_t Temperature2 : 8; /* scaling 1.0, offset -40.0, units degC  */
	uint16_t Voltage2 : 16; /* scaling 0.1, offset 0.0, units V  */
} SvrRpt1_t;

typedef struct {
	uint8_t VehStat : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EngFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TransFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t AirBrkFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EngBrkFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LightsFail : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SteerFail : 1; /* scaling 1.0, offset 0.0, units none  */
} AutoRpt_t;

typedef struct {
	uint8_t VINNum : 8; /* scaling 1.0, offset 0.0, units none  */
} VINRpt_t;

typedef struct {
	uint8_t VCU_version : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t feature_version : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t patch_version : 8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t truck_type : 8; /* scaling 1.0, offset 0.0, units none  */
} VCU_Version_t;

typedef struct {
	uint8_t Emgcy_Ord : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t St_Ord : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BrkEBI_Ord : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Tht_Ord : 1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Cruse_Ord : 1; /* scaling 1.0, offset 0.0, units none  */
} OrdStatus_t;

typedef struct {
	int16_t WP_x : 16; /* scaling 0.0, offset 0.0, units m  */
	int16_t WP_y : 16; /* scaling 0.0, offset 0.0, units m  */
} PlanningInfo1_t;

typedef struct {
	int16_t NovatelNorthVelocity : 16; /* scaling 0.0, offset 0.0, units none  */
	int16_t NovatelEastVelocity : 16; /* scaling 0.0, offset 0.0, units none  */
	int16_t NovatelAltitude : 16; /* scaling 0.1, offset 1600.0, units none  */
	int16_t NovatelPitch : 16; /* scaling 0.0, offset 0.0, units none  */
} LocalInfo1_t;

typedef struct {
	int32_t NovatelLatitude : 32; /* scaling 0.0, offset 35.0, units deg  */
	int32_t NovatelLongitude : 32; /* scaling 0.0, offset -100.0, units deg  */
} LocalInfo2_t;

typedef struct {
	int16_t Ax : 16; /* scaling 0.0, offset 0.0, units m/s^2  */
	int16_t Ay : 16; /* scaling 0.0, offset 0.0, units m/s^2  */
	int16_t YawRate : 16; /* scaling 0.0, offset 0.0, units rad/s  */
	int8_t RollRate : 8; /* scaling 0.0, offset 0.0, units rad/s  */
	int8_t PitchRate : 8; /* scaling 0.0, offset 0.0, units rad/s  */
} IMUInfo_t;

typedef struct {
	uint8_t LeftTurnSignalLightsRpt : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RightTurnSignalLightsRpt : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HazardLightRpt : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LowBeamHeadLightRpt : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HighBeamHeadLightRpt : 2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TurnSignalLightsDriverCmd : 2; /* scaling 1.0, offset 0.0, units none  */
} AcsyRpt_t;


#ifdef __cplusplus
} 
#endif

#endif
