/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef DOUBLE_SIGNAL_H
#define DOUBLE_SIGNAL_H

#include <stdint.h>


#ifdef __cplusplus
extern "C" { 
#endif

typedef struct {
	double DoubleSignal0; /* scaling 1.0, offset 0.0, units none , floating */
} NewMessage0_t;




#ifdef __cplusplus
} 
#endif

#endif
